//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMovies.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Users WHERE login=\'[login]\' AND password=\'[password]\';")]
        public string SelectUser {
            get {
                return ((string)(this["SelectUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ORDER BY ")]
        public string OrderBy {
            get {
                return ((string)(this["OrderBy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Cast(Cast(newid() AS binary(3)) AS int) as NextID")]
        public string NewId {
            get {
                return ((string)(this["NewId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Tags WHERE category = \'[category]\' ORDER BY name ASC")]
        public string SelectAllTags {
            get {
                return ((string)(this["SelectAllTags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Tags WHERE tagId = \'[id]\'")]
        public string SelectTagByID {
            get {
                return ((string)(this["SelectTagByID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Customers WHERE customerId=\'[id]\' ")]
        public string SelectCustomerByID {
            get {
                return ((string)(this["SelectCustomerByID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Customers ")]
        public string SelectAllFromCustomers {
            get {
                return ((string)(this["SelectAllFromCustomers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Customers WHERE forename LIKE \'%[name]%\' AND surname LIKE \'%[surnam" +
            "e]%\' and pesel LIKE \'%[pesel]%\' and phone like \'%[phone]%\' and address like \'%[a" +
            "ddress]%\' ")]
        public string SearchCustomers {
            get {
                return ((string)(this["SearchCustomers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Movies ")]
        public string SelectAllFromMovies {
            get {
                return ((string)(this["SelectAllFromMovies"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Movies WHERE moviesId=\'[id]\' ")]
        public string SelectMovieByID {
            get {
                return ((string)(this["SelectMovieByID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Tags WHERE name LIKE \'%[name]%\' AND category = \'[category]\' ORDER B" +
            "Y name ASC")]
        public string SearchTags {
            get {
                return ((string)(this["SearchTags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM MoviesTags")]
        public string SelectAllMoviesTags {
            get {
                return ((string)(this["SelectAllMoviesTags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * from Tags WHERE tagId IN (SELECT tagId FROM MoviesTags WHERE movieId = \'" +
            "[id]\') AND category = \'[category]\'")]
        public string SelectTagsByMovieId {
            get {
                return ((string)(this["SelectTagsByMovieId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM MoviesTags WHERE tagId = \'[id]\'")]
        public string SelectMoviesTagsByTagID {
            get {
                return ((string)(this["SelectMoviesTagsByTagID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT * FROM Movies 
WHERE 
title LIKE '%[title]%' AND
releaseYear LIKE '%[year]%' AND
country LIKE '%[country]%' AND
(('%[director]%' = '%%' OR moviesId IN (SELECT movieid FROM MoviesTags WHERE tagId IN (SELECT tagId FROM Tags WHERE name LIKE '%[director]%' AND category = 'Writer'))) AND
('%[genre]%' = '%%' OR moviesId IN (SELECT movieid FROM MoviesTags WHERE tagId IN (SELECT tagId FROM Tags WHERE name LIKE '%[genre]%' AND category = 'Genre'))) AND
('%[actor]%' = '%%' OR moviesId IN (SELECT movieid FROM MoviesTags WHERE tagId IN (SELECT tagId FROM Tags WHERE name LIKE '%[actor]%' AND category = 'Actor'))))")]
        public string SearchMoviesWithTheseTags {
            get {
                return ((string)(this["SearchMoviesWithTheseTags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * from DVDs WHERE dvdid IN (SELECT dvdid FROM DVDs WHERE movieId = \'[id]\')" +
            "")]
        public string SelectDVDByMovieId {
            get {
                return ((string)(this["SelectDVDByMovieId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * FROM DVDs ")]
        public string SelectAllDVDs {
            get {
                return ((string)(this["SelectAllDVDs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM DVDs WHERE dvdid = \'[id]\' ")]
        public string SelectDVDsById {
            get {
                return ((string)(this["SelectDVDsById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM DVDs WHERE movieid = \'[id]\' AND status = \'[status]\' ")]
        public string CountDVDsByStatus {
            get {
                return ((string)(this["CountDVDsByStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Limits")]
        public string GetLimits {
            get {
                return ((string)(this["GetLimits"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM RentingRecord WHERE customerid = \'[id]\'")]
        public string GetRentingRecordByCustomerId {
            get {
                return ((string)(this["GetRentingRecordByCustomerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT dvdid FROM DVDs WHERE status = \'Dostepny\' AND movieid = \'[id]\' ")]
        public string GetAvailableDVDByMovieId {
            get {
                return ((string)(this["GetAvailableDVDByMovieId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM RentingRecord")]
        public string GetAllRentingRecord {
            get {
                return ((string)(this["GetAllRentingRecord"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Movies WHERE moviesid = (SELECT movieid FROM DVDs WHERE dvdid = \'[i" +
            "d]\')")]
        public string GetMovieTitle {
            get {
                return ((string)(this["GetMovieTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM RentingRecord WHERE id = [id]")]
        public string GetTransactionById {
            get {
                return ((string)(this["GetTransactionById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM RentingRecord WHERE dvdid = [id]")]
        public string GetTransactionsByDVDId {
            get {
                return ((string)(this["GetTransactionsByDVDId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM MoviesTags WHERE tagId = \'[tagid]\' AND movieid = \'[movieid]\' ")]
        public string SelectMoviesTagsByTagAndMovieId {
            get {
                return ((string)(this["SelectMoviesTagsByTagAndMovieId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFileName=|DataDirectory|\\Database.mdf;Integrated" +
            " Security=True;User Instance=True;MultipleActiveResultSets=True")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
        }
    }
}
